# Generated by Django 6.0.1 on 2026-01-17 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_aipkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aipkey',
            new_name='Apikey',
        ),
    ]
