# Generated by Django 6.0.1 on 2026-02-26 00:15

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('app_limit', models.PositiveIntegerField(default=1)),
                ('monthly_request_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120)),
                ('current_period_start', models.DateField(default=datetime.date.today)),
                ('current_period_end', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='billing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('api_requests', 'API requests'), ('apps', 'Apps')], max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='orgs.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'metric', 'period_start', 'period_end'), name='unique_usage_per_org_metric_period')],
            },
        ),
    ]
